package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);

    //根据userId和productId查询购物信息
    Cart selectCartByUseridAndProductid(@Param("userId") Integer userId,
                                        @Param("productId") Integer productId);

    //根据userId查询购物车信息
    List<Cart> selectCartByUserid(Integer userId);

    //统计用户购物是否全选
    //返回值大于0，未全选
    int isCheckedAll(Integer userId);

    int deleteByUseridAndProductIds(
            @Param("userId") Integer userId,
            @Param("productIdList") List<Integer> productIdList);

    /**
     * 选中或取消选中
     * product为空时，全选或全不选
     *不为空时，对单个商品的操作
     */
    int selectOrUnselectProduct(
            @Param("userId") Integer userId,
            @Param("productId") Integer productId,
            @Param("check") Integer check);

    //查询购物车中商品数量
    int get_cart_product_count(Integer userId);

    //查询购物车中已被选中的商品
    List<Cart> findByUseridAndChecked(Integer userId);

    //购买完批量删除购物车中的商品
    int batchDelete(List<Cart> cartList);
}