package com.neuedu.dao;

import com.neuedu.pojo.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Order record);

    //根据用户id和订单编号来查找订单
    Order findOrderByUseridAndOrderno(@Param("userId") Integer userId,
                                      @Param("orderNo") Long orderNo);

    //根据用户id查询订单
    List<Order> findOrderByUserid(Integer userId);

    //根据用户id和订单状态查询订单
    List<Order> findOrderByUseridAndOrderstatus(@Param("userId") Integer userId,
                                                @Param("orderStatus") Integer orderStatus);

    //根据订单号查询订单
    Order findOrderByOrderno(Long orderNo);

    //根据订单号修改订单的状态和支付时间
    int updateOrderstatusAndPaymenttimeByOrderno(@Param("order") Order order);
}