package com.neuedu.dao;

import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int insert(@Param("user") UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(@Param("user") UserInfo record);

    /**判断用户名是否存在
     * @return 1:存在 0:不存在
     *
     */
    int existUsername(@Param("username") String username);

    int existEmail(@Param("email") String email);

    String findQuestionByUsername(@Param("username") String username);
    int checkAnswer(@Param("username") String username,
                    @Param("question") String question,
                    @Param("answer") String answer);
    int resetPassword(@Param("username") String username,@Param("password") String password);

    int checkUsername(@Param("username") String username);

    int checkEmail(@Param("email") String email);

    UserInfo findByUsernameAndPassword(@Param("user") UserInfo userInfo);
}