package com.neuedu.dao;

import com.neuedu.entity.Userinfo;
import org.apache.ibatis.annotations.Param;

public interface UserinfoMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table neuedu_user
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table neuedu_user
//     *
//     * @mbggenerated
//     */

    /**
     *  新增用户信息
     * @param record
     * @return
     */
    int insert(@Param("userInfo") Userinfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table neuedu_user
//     *
//     * @mbggenerated
//     */
//    UserInfo selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table neuedu_user
//     *
//     * @mbggenerated
//     */
//    List<UserInfo> selectAll();
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table neuedu_user
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(@Param("user") UserInfo record);
//
//    /**判断用户名是否存在
//     * @return 1:存在 0:不存在
//     *
//     */
//    int existUsername(@Param("username") String username);
//

    /**
     *   判断身份证号是否存在
     * @param userinfoIdcard
     * @return
     */
    int existUserinfoIdcard(@Param("userinfoIdcard") String userinfoIdcard);

    /**
     *  根据身份证号查询用户信息
     * @param userinfoIdcard
     * @return
     */
    Userinfo selectUserInfoByIdCard(@Param("userinfoIdcard") String userinfoIdcard);
//
//    String findQuestionByUsername(@Param("username") String username);
//    int checkAnswer(@Param("username") String username,
//                    @Param("question") String question,
//                    @Param("answer") String answer);
//    int resetPassword(@Param("username") String username,@Param("password") String password);
//
//    int checkUsername(@Param("username") String username);
//
//    int checkEmail(@Param("email") String email);
//
//    UserInfo findByUsernameAndPassword(@Param("user") UserInfo userInfo);
}