package com.neuedu.dao;

import com.neuedu.entity.User;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table neuedu_user
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table neuedu_user
//     *
//     * @mbggenerated
//     */

    /**
     * 新增用户
     * @param record
     * @return
     */
    int insert(@Param("user") User record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table neuedu_user
//     *
//     * @mbggenerated
//     */
//    UserInfo selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table neuedu_user
//     *
//     * @mbggenerated
//     */
//    List<UserInfo> selectAll();
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table neuedu_user
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(@Param("user") UserInfo record);


    /**
     *  判断登录用户名是否存在
     * @param userName
     * @return 1:存在 0:不存在
     */
    int existUserNameOrEmail(@Param("userName") String userName);

    /**
     *  判断用户名是否存在
     * @param userName
     * @return 1:存在 0:不存在
     */
    int existUserName(@Param("userName") String userName);

    /**
     *  判断邮箱是否存在
     * @param userEmail
     * @return 1:存在 0:不存在
     */
    int existUserEmail(@Param("userEmail") String userEmail);
//
//    String findQuestionByUsername(@Param("username") String username);
//    int checkAnswer(@Param("username") String username,
//                    @Param("question") String question,
//                    @Param("answer") String answer);
//    int resetPassword(@Param("username") String username, @Param("password") String password);
//
//    int checkUsername(@Param("username") String username);
//
//    int checkEmail(@Param("email") String email);

    User findByUsernameAndPassword(@Param("user") User user);
}